# Generated by Django 4.1.2 on 2022-10-25 16:00

import django.core.validators
from django.db import migrations, models
import my_music_app.music.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
