# Generated by Django 4.1.2 on 2022-10-25 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_create_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "album_name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Album Name"
                    ),
                ),
                ("artist", models.CharField(max_length=30)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Pop Music", "Pop Music"),
                            ("Jazz Music", "Jazz Music"),
                            ("R&B Music", "R&B Music"),
                            ("Rock Music", "Rock Music"),
                            ("Country Music", "Country Music"),
                            ("Dance Music", "Dance Music"),
                            ("Hip Hop Music", "Hip Hop Music"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(verbose_name="Image URL")),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
            ],
        ),
    ]
