# Generated by Django 4.1.2 on 2022-10-28 13:39

import django.core.validators
from django.db import migrations, models
import expenses.expenses_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = []
