# Generated by Django 4.1.2 on 2022-10-28 18:38

from django.db import migrations, models
import expenses.expenses_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses_app", "0003_expenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                validators=[expenses.expenses_app.models.validator_max_size_image],
            ),
        ),
    ]
