# Generated by Django 4.1.2 on 2022-10-30 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Sports Car", "Sports Car"),
                            ("Pickup", "Pickup"),
                            ("Crossover", "Crossover"),
                            ("Minibus", "Minibus"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1980, "Year must be between 1980 and 2049"
                            ),
                            django.core.validators.MaxValueValidator(
                                2049, "Year must be between 1980 and 2049"
                            ),
                        ]
                    ),
                ),
                ("image_url", models.URLField(verbose_name="Image URL")),
                (
                    "price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
        ),
    ]
