# Generated by Django 4.1.2 on 2022-10-30 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0003_car"),
    ]

    operations = [
        migrations.AlterModelOptions(name="car", options={"ordering": ("pk",)},),
    ]
