# Generated by Django 4.1.2 on 2022-10-27 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(5.0),
                ]
            ),
        ),
    ]
