# Generated by Django 4.1.2 on 2022-10-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_game_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(name="game", options={"ordering": ("pk",)},),
    ]
