# Generated by Django 4.1.2 on 2022-10-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_app", "0003_note"),
    ]

    operations = [
        migrations.RemoveField(model_name="note", name="context",),
        migrations.AddField(
            model_name="note",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="image_url",
            field=models.URLField(verbose_name="Link to Image"),
        ),
    ]
