# Generated by Django 4.1.2 on 2022-10-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes_app", "0004_remove_note_context_note_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="note", options={"ordering": ("pk",)},),
    ]
